/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import BLL.*;
import DTO.*;
import java.sql.*;
import Utils.DBUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author huynh
 */
public class DatPhongUI_test_screen extends javax.swing.JFrame {

    /**
     * Creates new form DatPhongUI2
     */
    public DatPhongUI_test_screen() {
        initComponents();
    }

    public int layBookingID(){
        int bookingID = 0;
        Connection con = new DBUtils().createConn();
        
        String strSQL = "select bookingid from booking order by bookingid desc";
        try{
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(strSQL);
            if(rs.next()==false){
                bookingID = 1;
            }
            else{
                int bookingIDHienTai = rs.getInt("bookingid");
                bookingID = bookingIDHienTai++;
            }
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return bookingID;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        dateNgayNhanPhong = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        ckbDatCoc = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbDangThue = new javax.swing.JComboBox<>();
        spnSLGiuong = new javax.swing.JSpinner();
        dateNgayDi = new com.toedter.calendar.JDateChooser();
        txtCMND = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDatPhong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnDatCoc = new javax.swing.JButton();
        cbbSoPhong = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Ngày đi");

        jLabel6.setText("CMND");

        ckbDatCoc.setText("Đã đặt cọc");
        ckbDatCoc.setEnabled(false);
        ckbDatCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbDatCocActionPerformed(evt);
            }
        });

        jLabel7.setText("Tên KH");

        jLabel8.setText("Ngày nhận phòng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin phòng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Thông tin khách hàng");

        jLabel3.setText("Dạng thuê");

        btnDatPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lượng giường");

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setText("Thoát");

        btnDatCoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDatCoc.setText("Đặt cọc");
        btnDatCoc.setEnabled(false);
        btnDatCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatCocActionPerformed(evt);
            }
        });

        jLabel9.setText("Số phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbDangThue, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSLGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnDatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ckbDatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnDatPhong)
                .addGap(47, 47, 47)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(13, 13, 13)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateNgayNhanPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbDangThue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnSLGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateNgayNhanPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbSoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbDatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        //         TODO add your handling code here:
                if(txtCMND.getText().equals("")||txtTenKH.getText().equals("")||Integer.parseInt(spnSLGiuong.getValue().toString())<1||
                            dateNgayDi.getDate().equals("")||dateNgayNhanPhong.getDate().equals("")){
                        JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin đặt phòng", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                    }
                else{
                        Connection con = new DBUtils().createConn();
                        BookingDTO booking = new BookingDTO();
                        booking.setBookingID(layBookingID());
                        booking.setCustomerID(Integer.parseInt(txtCMND.getText()));
                        booking.setRoomID(Integer.parseInt(cbbSoPhong.getSelectedItem().toString()));
                        java.util.Date utilDate = dateNgayDi.getDate();
                        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                        booking.setStartDate(sqlDate);
                        utilDate = dateNgayNhanPhong.getDate();
                        sqlDate = new java.sql.Date(utilDate.getTime());
                        booking.setEndDate(sqlDate);
            
                        BookingBLL bookingBll = new BookingBLL();
                        try{
                                int result = bookingBll.insertBooking(booking);
                                if(result!=0){
                                        JOptionPane.showMessageDialog(null, "Book thành công, vui lòng ghi nhận đặt cọc","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                                        btnDatCoc.setEnabled(true);
                                        btnDatPhong.setEnabled(false);
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Book không thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                                    }
                            }catch(Exception e){
                                e.printStackTrace();
                            }
                    }
        //testing
        this.btnDatCoc.setEnabled(true);
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void ckbDatCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbDatCocActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ckbDatCocActionPerformed

    private void btnDatCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatCocActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        TTDatCocUI_test_screen datCocFrm = new TTDatCocUI_test_screen(this.txtTenKH.getText(), this.txtCMND.getText());
        datCocFrm.setVisible(true);
//                while(!datCocFrm.isVisible()){
//                        int bookingID = 0;
//                        Connection con = new DBUtils().createConn();
//                        String strSQL = "select bookingID from booking where customerid = '"+txtCMND.getText()+"'";
//                        try{
//                                Statement stat = con.createStatement();
//                                ResultSet rs = stat.executeQuery(strSQL);
//                                while(rs.next()){
//                                        bookingID = rs.getInt("bookingid");
//                                    }
//                            }
//                        catch(Exception e){
//                                e.printStackTrace();
//                            }
//                        strSQL = "select depositid from deposit where bookingid = "+bookingID;
//                        try{
//                                Statement stat = con.createStatement();
//                                ResultSet rs = stat.executeQuery(strSQL);
//                                if(rs.next()){
//                                        this.ckbDatCoc.setSelected(true);
//                                        this.btnDatCoc.setEnabled(false);
//                                        this.cbbDangThue.setEnabled(false);
//                                        this.cbbSoPhong.setEnabled(false);
//                                        this.spnSLGiuong.setEnabled(false);
//                                        this.txtCMND.setEditable(false);
//                                        this.txtTenKH.setEditable(false);
//                                        this.dateNgayNhanPhong.setEnabled(false);
//                                        this.dateNgayDi.setEnabled(false);
//                                    }
//                            }
//                        catch(Exception e){
//                                e.printStackTrace();
//                            }
//                        this.btnDatCoc.setEnabled(false);
//                        break;
//                    }
        //testing
        this.btnDatCoc.setEnabled(false);
    }//GEN-LAST:event_btnDatCocActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatPhongUI_test_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatPhongUI_test_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatPhongUI_test_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatPhongUI_test_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatPhongUI_test_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatCoc;
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox<String> cbbDangThue;
    private javax.swing.JComboBox<String> cbbSoPhong;
    private javax.swing.JCheckBox ckbDatCoc;
    private com.toedter.calendar.JDateChooser dateNgayDi;
    private com.toedter.calendar.JDateChooser dateNgayNhanPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnSLGiuong;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
